name: 'github actions build and deploy gh-pages'
on:
  push:
    branches:
      - master
      - feature/upgrade-vuepress2
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: install and build
        run: |
          npm install
          npm run build
          cp README.md .site/
      - name: "Deploy Github"
        uses: s0/git-publish-subdir-action@master
        env:
          REPO: git@github.com:binghe001/binghe001.github.io.git
          BRANCH: master
          FOLDER: .site
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
      - name: Sync to Gitcode
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:binghe001/binghe001.github.io.git
          destination-repo: git@gitcode.net:binghe/binghe.gitcode.host.git
